// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xynxahqjtvgeylkojwop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bnhhaHFqdHZnZXlsa29qd29wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTQ2MjYsImV4cCI6MjA3MjgzMDYyNn0.djhYiY-jt536Hm3Ns5XFwSqubxUvubYEIJxc7Ra8W6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});